### ISSUE TITLE
Chapter 2 docker image file example has an error

### ISSUE THREAD

**Issue by MauriMatamoros** [PacktPublishing/Mastering-Docker-Second-Edition#2]
`FROM alpine:latest
LABEL maintainer="Russ McKendrick <russ@mckendrick.io>"
LABEL description="This example Dockerfile installs NGINX."
RUN apk add --update nginx && \
        rm -rf /var/cache/apk/* && \
        mkdir -p /tmp/nginx/

COPY files/nginx.conf /etc/nginx/nginx.conf
COPY files/default.conf /etc/nginx/conf.d/default.conf
ADD files/html.tar.gz /usr/share/nginx/

EXPOSE 80/tcp

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]`

execution fails
with this: `docker image build --tag local:dockerfile-example .`

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if the issue still persists
